#pragma once

namespace breakdown::utils {

    constexpr std::array WITTY_COMMENTS = {
        "Everything's going to plan. No, really, that was supposed to happen.",
        "Uh... Did I do that?",
        "Oops.",
        "Why did you do that?",
        "I feel sad now :(",
        "My bad.",
        "Time to uninstall some mods!",
        "I let you down. Sorry :(",
        "On the bright side, I bought you a teddy bear!",
        "Your Mega Hack crashed! (Just kidding)",
        "Oh - I know what I did wrong!",
        "Hey, that tickles! Hehehe!",
        "I blame RobTop",
        "Don't be sad. I'll do better next time, I promise!",
        "Don't be sad, have a hug! <3",
        "I just don't know what went wrong :(",
        "Shall we play a game?",
        "I bet Cvolton wouldn't have this problem.",
        "Quite honestly, I wouldn't worry myself about that.",
        "Sorry :(",
        "Surprise! Haha. Well, this is awkward.",
        "Would you like a cupcake?",
        "This doesn't make any sense!",
        "Why is it breaking :(",
        "Don't do that.",
        "Ouch. That hurt :(",
        "You're mean.",
        "But it works on my machine.",
        "Hi Absolute!",
        "The chicken is on fire!",
        "I've accidentally crashed the game! /RubRub",
        "It's a feature, not a bug!",
        "Try turning it off and on again.",
        "Boo!",
        "Whoopsies! An unhandled exception has occurred.",
        "Geometry Dash isn't Geometry Dashing anymore",
        "$ sudo rm -rf /",
        "To the mod developer: Please 309 yourself",
        "Let's pretend this didn't happen.",
        "I hope it's not GJRobotSprite::init this time",
        "Skill issue",
        "Out of cheese error.",
        "Error 404: Fun not found.",
        "A wild bug appeared!",
        "Congratulations! You found a bug.",
        "Don't panic! It's just a minor setback.",
        "Cosmic rays caused a bit flip, sorry!",
        "I'm not crying, you're crying.",
        "Insert witty error message here.",
        "Mission failed successfully.",
        "Game over. Insert coin to continue.",
        "You shall not pass! Oh wait, you did...",
        "The cake is a lie!",
        "Quick, look over there! *runs away*",
        "To be continued...",
        "In case of fire, use water.",
        "Did you try blowing on the cartridge?",
        "You found an easter egg! Just kidding, it's a crash.",
        "Have you tried yelling at the screen?",
        // Platform-specific witty comments
#ifdef GEODE_IS_WINDOWS
        "Now in 64 bits!",
        "Windows Defender couldn't defend this crash.",
        "Did you forget to run as administrator?",
        "Oh no, another CrowdStrike kernel driver crash!",
        "At least it's not a Blue Screen of Death this time.",
        "This is fine. *Windows error sound*",
        "Would you like to search Bing for a solution?",
        "Fun fact: this crash increases your pagefile usage!",
#elif defined(GEODE_IS_MAC)
        "Ask your local Apple Store for help!",
        "Mac users are too cool to crash... oh wait.",
        "Don't blame me, blame the overpriced hardware!",
        "Think different? Well, this crash certainly is.",
        "Crash Diagnostics is now collecting your soul... I mean, logs.",
    #ifdef GEODE_IS_ARM_MAC
        "Apple Silicon is powerful... except when it's not.",
        "Who needs fans when you can have this hot crash?",
        "Guess it wasn't 'Pro' enough to avoid crashing.",
        "M1, more like M-done.",
        "M2 Ultra? More like M-too broken.",
    #else
        "Blame Intel for this one.",
        "Did the thermal paste give up?",
        "Intel Inside, trouble outside.",
        "This crash requires macOS 15.1.1 or later to run.",
        "Remember when they called it 'Macintosh'? Good times.",
        "Crash delivered at 2.6 GHz per core.",
    #endif
#endif
    };

}